#!/usr/bin/env bash

# Update the package list and install Nginx
apt-get -y update
apt-get -y install nginx

# Create a simple HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Check if Nginx is running and start it if not
if ! pgrep -x "nginx" > /dev/null; then
    /usr/sbin/nginx
fi
